# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest

# cache is used to specify a list of files and directories which should be cached between jobs. You can only use paths that are within the project workspace.
# If cache is defined outside the scope of jobs, it means it is set globally and all jobs will use that definition
#cache:
#  paths:
# before_script is used to define the command that should be run before all jobs, including deploy jobs, but after the restoration of artifacts.
# This can be an array or a multi-line string.
before_script:
  - python3 -m pip install -r requirements-dev.txt
  - python3 -m pip install pipdeptree

stages:
  - linting
  - test
  - docs
  - package
  - publish
  - deploy

test:
  stage: test
  tags:
    - docker-executor
  script:
    - tox -e py37
  artifacts:
    paths:
      - ./build

list_dependencies:
  tags:
    - docker-executor
  stage: test
  script:
    - pipdeptree --json >> pip_deps.json
    - pipdeptree >> pip_deps.txt
    - mkdir .public
    - cp pip_deps.txt .public/
    - cp pip_deps.json .public/
    - mv .public public
  artifacts:
    paths:
      - public

linting:
  tags:
    - docker-executor
  stage: linting
  script:
    - tox -e lint
  when: always
  artifacts:
    paths:
      - ./build

docs:
  tags:
    - docker-executor
  stage: docs
  before_script:
    - echo "error" > .docs_status
    - python3 -m pip install -r requirements-dev.txt
    - python3 -m pip install anybadge
  script:
    - tox -e docs
    - echo "pass" > .docs_status
  after_script:
    - mkdir -p build/badges
    - anybadge --label=docs --value=$(cat .docs_status) --file=build/badges/docs.svg pass=green error=red
  artifacts:
    paths:
      - ./build
      - ./docs/build/html
    when: always
    expire_in: 7 days

build wheel:
  stage: package
  tags:
    - docker-executor
  script:
    # check metadata requirements
    - pip3 install katversion
    - scripts/validate-metadata.sh
    - tox -e package
  artifacts:
    paths:
      - ./dist

publish package to nexus:
  stage: publish
  tags:
    - docker-executor
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
    PACKAGE_TAG: $CI_COMMIT_SHORT_SHA
  script:
    # check metadata requirements
    #- scripts/validate-metadata.sh
    - python3 -m pip install twine
    - tox -e package # takes $PACKAGE_TAG as input
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/*
  only:
    refs:
      - tags
    variables:
      # Confirm tag message exists
      - $CI_COMMIT_MESSAGE =~ /^.+$/
      # Confirm semantic versioning of tag
      - $CI_COMMIT_TAG =~ /^((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$/

pages:
  stage: deploy
  tags:
    - docker-executor
  dependencies:
    - test
  script:
    - ls -la
    - mkdir .public
    - cp -r ./build/htmlcov/* .public
    - mv .public public
  artifacts:
    paths:
      - public
    expire_in: 30 days

create ci metrics:
  stage: .post
  image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest
  when: always
  tags:
    - docker-executor
  script:
    # Gitlab CI badges creation: START
    - apt-get -y update
    - apt-get install -y curl --no-install-recommends
    - curl -s https://gitlab.com/ska-telescope/ci-metrics-utilities/raw/master/scripts/ci-badges-func.sh | sh
    # Gitlab CI badges creation: END
  artifacts:
    paths:
      - ./build


